### ISSUE TITLE
Extra line in raw(read(file))

### ISSUE THREAD

**Issue by tete-github** [Dherse/codly#30]
My codly is 1.0.0 .
When using #raw(read(file), block: true) extra line with a line number appears at the end of the code block.

Probably an issue of Typst 0.11.1 (installed via nix on SteamOS), because the same thing happens when I use this simple rule instead.
```
#show raw.where(block: true): code => {
  show raw.line: line => {
    text(fill: gray)[#line.number]
    h(1em)
    line.body
  }
  code
}
```

Can't reproduce this behavior in the web app.

My fix was downloading codly and adding `or line.number == line.count` to
```
      if not in_range(line.number) {
        continue
      }
```

Is there a better way?
Seems like work is being done on line numbers [in typst itself](https://github.com/typst/typst/pull/4516).

**Comment by Dherse** [comment]
Just to mention, the PR you listed is lines but not specifically for code, the original work to make line numbers for raw blocks was in https://github.com/typst/typst/pull/2341

As for the extra line, does your file contain it? Bit of a dumb question but I would rather check that first. Also, if it's an issue with typst v0.11 and fixed in v0.11.1, see what I mean here: https://typst.app/project/rq9BcVmddB0jX80iQ3679R If I put a newline at the end of the `read` file, it will show up but that's just how it is. Your solution just removes the last line and therefore could break other code blocks.

**Comment by tete-github** [comment]
> As for the extra line, does your file contain it? Bit of a dumb question but I would rather check that first.

A very well placed question and the first one I asked myself too.
Unfortunately, no, there is only one line feed character at the end of the files.
Is that how it should be? Maybe it's [a Posix thing](https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file)?

>  Your solution just removes the last line and therefore could break other code blocks.
If only I could use "range" and "skips" based on their number counting from the end of file.

**Comment by tete-github** [comment]
It turns out [read returns string](https://typst.app/docs/reference/data-loading/read) and I can just slice it with the Typst built-in function to cut off the last lines.
```
#let solution = read(sql_path + "spool.txt").slice(0, -1)
#raw(solution, block: true)
```

**Comment by Dherse** [comment]
> If only I could use "range" and "skips" based on their number counting from the end of file.
That's actually a pretty neat idea
